name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
      - name: Set git config
        run: |
          git config user.name Alexis
          git config user.email alexis@georges.brussels

      - name: List git config
        run: |
          git config user.name
          git config user.email