name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:       
      - name: Set git config
        run: |
          git config --global user.name Alexis
          git config --global user.email alexis@georges.brussels

      - name: List files
        run: |
          echo "$(ls ./)"
          echo "$(ls)"
          cat script.sh
      - name: Run script update-packages
        run: bash ./script.sh
