name: CI

on:
  push:
    branches:
      - master
    tags:
      - '*'
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:       
      - uses: actions/checkout@v1
      - name: Set git config
        run: |
          git config --global user.name Alexis
          git config --global user.email alexis@georges.brussels

      - name: List files
        run: |
          echo "$(ls ./)"
          echo "$(ls)"
          cat script.sh

      - name: Run script update-packages
        run: bash ./script.sh
      
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
